Polygon Overlay
TileDB-Inc/TileDB-Viz pull request #135
Opened 2023-09-12 14:26 UTC by XanthosXanthopoulos

This PR adds support for rendering geometry overlay on top of tile images. Currently only polygon are support that are stored in WKB format.
To align the geometry and the tile images, both the CRS of the geometry and of the images needs to be in the metadata as well as the transformation coefficient to translate from the image space to the image CRS

2023-09-15 11:01 UTC, SarantopoulosKon requested changes

2023-09-15 14:56 UTC, XanthosXanthopoulos commented on packages/core/src/tile/model/image/minimap.ts
> +    implements UpdateOperation<MinimapManager>
This is to be removed by the next PR

2023-09-19 08:11 UTC, SarantopoulosKon commented
Trying to run it again but i get `imageManager.ts:164 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')`

2023-09-25 08:21 UTC, SarantopoulosKon approved these changes

2023-09-25 08:23 UTC, merged